services:
  application:
    container_name: "mysite"
    build:
      context: ./docker/
      dockerfile: Dockerfile
    command: "npm run watch"
    volumes:
      - ./:/var/www
    networks:
        - project-site
    ports:
      - 8000:3000

networks:
    project-site:
        driver: bridge
