services:
  application:
    container_name: "mysite"
    build:
      context: ./docker/
      dockerfile: Dockerfile
    command: "vendor/bin/jigsaw serve --port=8000 --host=0.0.0.0"
    volumes:
      - ./:/var/www
    networks:
        - project-site
    ports:
      - 8000:8000

networks:
    project-site:
        driver: bridge
